const URLS = {};
URLS.ACCUEIL = "/";
URLS.CONNEXION = URLS.ACCUEIL + "connexion/";
URLS.INSCRIPTION = URLS.ACCUEIL + "inscription/";
URLS.INSCRIPTION_ETABLISSEMENT = URLS.INSCRIPTION + "etablissement/";
URLS.INSCRIPTION_MEDECIN = URLS.INSCRIPTION + "medecin/";

export default URLS;
