const URLS = {};
URLS.ACCUEIL = "/";
URLS.CONNEXION = URLS.ACCUEIL + "connexion/";
URLS.INSCRIPTION = URLS.ACCUEIL + "inscription/";
URLS.INSCRIPTION_ETABLISSEMENT = URLS.INSCRIPTION + "etablissement/";
URLS.INSCRIPTION_MEDECIN = URLS.INSCRIPTION + "medecin/";
URLS.AJOUTLIEU = URLS.ACCUEIL + "ajoutLieu/";
URLS.QRCODES = URLS.ACCUEIL + "qrcodes/";

export default URLS;
